Repository BHoM/Grasshopper_UI, pull requests merged in 2019-04, with the labels that each got.

#344 Update post build events to centralise assemblies location
  Grasshopper_UI/Grasshopper_UI.csproj
Labels: severity:medium, size:M, status:do-not-merge, type:feature

#346 Casting to RHG.Surface for Polysurface ToRhino
  Grasshopper_Engine/Compute/RenderMeshes.cs
  Grasshopper_Engine/Compute/RenderWires.cs
  Grasshopper_UI/2.0/NonComponents/Render/RenderBHoMGeometry.cs
Labels: type:external-api-changes

#349 Rendering ISolid
  Grasshopper_Engine/Compute/RenderRhinoMesh.cs
  Grasshopper_Engine/Compute/RenderRhinoWires.cs
Labels: severity:medium, size:S, type:feature
