Repository BHoM/Grasshopper_UI, pull requests merged in 2019-05, with the labels that each got.

#352 Postbuild events fail if path contains a space
  Grasshopper_UI/Grasshopper_UI.csproj
Labels: severity:critical, type:bug

#359 use global address when copying files over
  Grasshopper_UI/Grasshopper_UI.csproj
Labels: status:do-not-merge, type:bug

#367 Rendering points and simplifying the RenderRhinoMeshes method
  Grasshopper_Engine/Compute/RenderRhinoMesh.cs
  Grasshopper_Engine/Compute/RenderRhinoWires.cs
Labels: severity:medium, type:feature

#368 Add the OLD label on deprecated methods
  Grasshopper_UI/2.1/Templates/CallerComponent.cs
Labels: good first issue, severity:low, type:bug
