Repository BHoM/Grasshopper_UI, pull requests merged in 2019-11, with the labels that each got.

#426 Update to the new version of the CreateObject component
  Grasshopper_UI/Components/oM/CreateObject.cs
Labels: type:feature

#434 Remove Testing_oM reference
  Grasshopper_UI/Grasshopper_UI.csproj
Labels: size:XS, type:compliance

#432 Refine the CreateObject component
  Grasshopper_UI/Components/oM/CreateObject.cs
  Grasshopper_UI/Templates/CallerComponent.cs
Labels: type:feature

#437 Add tolerance for casing in input selection through menu
  Grasshopper_UI/Components/oM/CreateObject.cs
Labels: type:feature

#442 Add support for lists as input default values
  Grasshopper_Engine/Convert/ToGoo.cs
  Grasshopper_UI/Templates/CallerComponent.cs
Labels: type:bug
