Repository BHoM/Grasshopper_UI, pull requests merged in 2020-05, with the labels that each got.

#505 Take care of input type that are both list and items
  Grasshopper_Engine/Convert/FromGoo.cs
Labels: type:bug

#510 Fixing compliance issues for csproj files
  GHManipulator_Alligator/GHManipulator_Alligator.csproj
  Grasshopper_Engine/Grasshopper_Engine.csproj
  Grasshopper_UI/Grasshopper_UI.csproj
Labels: type:compliance

#513 Fix duplicate components after unload & reload of GH
  Grasshopper_UI/Global/GlobalSearch.cs
Labels: type:bug

#514 Update repo ReadMe.md file
  README.md
Labels: type:documentation

#515 Stop adding component search items here as handled in BHoM_UI
  Grasshopper_UI/Global/GlobalSearch.cs
Labels: type:feature
