Repository BHoM/Grasshopper_UI, pull requests merged in 2020-03, with the labels that each got.

#476 Fix incorrect wire creation on component created from global menu
  Grasshopper_UI/Global/GlobalSearch.cs
Labels: type:bug

#483 Update description of multi choice component after a value has been picked.
  Grasshopper_UI/Templates/CallerValueList.cs
Labels: type:feature

#487 Update CI Files
  .ci/check-all-depandants.yml
  .ci/check-core.yml
  .ci/check-installer.yml
  .ci/run-compliance-tests.yml
Labels: type:compliance

#479 Add detection of incorrect group structure in Node2Code
  Grasshopper_Engine/Convert/ToNodeGroup.cs
  Grasshopper_UI/Components/UI/Cluster2Node.cs
Labels: type:bug

#486 Add versioning for ValueList component
  Grasshopper_UI/Templates/CallerValueList.cs
Labels: severity:critical, type:feature

#490 Fix message notes covering all other messages
  Grasshopper_UI/Others/Logging.cs
  Grasshopper_UI/Templates/CallerComponent.cs
Labels: type:bug
