Repository BHoM/Grasshopper_UI, pull requests merged in 2020-11, with the labels that each got.

#564 Grasshopper toolkit: Keeping flattening settings when replacing an input/output
  Grasshopper_UI/CallerComponent/OncallerModified.cs
Labels: type:bug

#566 Adding GetEvents component
  Grasshopper_UI/Components/Engine/GetEvents.cs
  Grasshopper_UI/Grasshopper_UI.csproj
Labels: type:feature

#572 Fix BHoM vectors not convertible to GH vectors
  Grasshopper_UI/Goos/GH_BakeableObject.cs
Labels: severity:critical, type:bug
